//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMS_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookIssue
    {
        public int BookIssueID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> FacultyID { get; set; }
        public Nullable<int> BookAvailable { get; set; }
        public Nullable<decimal> Fine { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual Student Student { get; set; }
    }
}
